name: Initial Test

on:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo "Test test/"
          echo 'something'
          exit 1
