name: On Failure

on:
  workflow_run:
    workflows: [Initial Test]
    types:
      - completed


jobs:
  failed:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' && startsWith(github.event.workflow_run.head_branch, 'test/') }}
    steps:
      - name: something
        run: |
          echo 'ran on failure'
          echo ${{ github.ref_name }}
          echo ${{ github.event.workflow_run.head_branch }}
          echo ${{ startsWith(github.ref_name, 'test/') }}
          echo ${{ startsWith(github.event.workflow_run.head_branch, 'test/') }}
    
